// ============================================================
// Campus Management System - Comprehensive Mock Data
// ============================================================

import type {
  User,
  Student,
  Teacher,
  Parent,
  Institute,
  Branch,
  Department,
  Program,
  AcademicYear,
  Term,
  Batch,
  Course,
  CourseModule,
  CourseLesson,
  Enrollment,
  AttendanceSession,
  AttendanceRecord,
  Assignment,
  Submission,
  Assessment,
  QuizAttempt,
  Grade,
  FeeInvoice,
  FeePayment,
  Announcement,
  Notification,
  Message,
  Conversation,
  LeaveRequest,
  SupportTicket,
  DocumentRequest,
  TimetableSlot,
  CalendarEvent,
  DashboardStats,
  SuperAdminDashboardStats,
  InstituteAdminDashboardStats,
  BranchAdminDashboardStats,
  TeacherDashboardStats,
  StudentDashboardStats,
  ParentDashboardStats,
  ActivityItem,
  UserRole,
} from "@/types";

// -------------------- Utility Helpers --------------------

function randomFrom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomBetween(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

function formatDate(date: Date): string {
  return date.toISOString().split("T")[0];
}

// -------------------- Institutes --------------------

export const mockInstitutes: Institute[] = [
  {
    id: "inst-001",
    name: "Greenfield Education Group",
    code: "GEG",
    address: "123 Education Avenue, Academic City",
    city: "Springfield",
    state: "Illinois",
    country: "United States",
    zipCode: "62701",
    phone: "+1-555-0100",
    email: "admin@greenfield.edu",
    website: "https://greenfield.edu",
    established: "1995",
    branchCount: 3,
    studentCount: 12500,
    teacherCount: 850,
    isActive: true,
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(1),
  },
  {
    id: "inst-002",
    name: "Oakridge Academic Network",
    code: "OAN",
    address: "456 Knowledge Park, Metro City",
    city: "Austin",
    state: "Texas",
    country: "United States",
    zipCode: "73301",
    phone: "+1-555-0200",
    email: "info@oakridge.edu",
    website: "https://oakridge.edu",
    established: "2005",
    branchCount: 2,
    studentCount: 8200,
    teacherCount: 560,
    isActive: true,
    createdAt: daysAgo(2555),
    updatedAt: daysAgo(3),
  },
  {
    id: "inst-003",
    name: "Sunrise Learning Foundation",
    code: "SLF",
    address: "789 Learning Lane, Harbor Town",
    city: "Seattle",
    state: "Washington",
    country: "United States",
    zipCode: "98101",
    phone: "+1-555-0300",
    email: "contact@sunrise.edu",
    established: "2010",
    branchCount: 1,
    studentCount: 3200,
    teacherCount: 210,
    isActive: true,
    createdAt: daysAgo(1825),
    updatedAt: daysAgo(7),
  },
];

// -------------------- Branches --------------------

export const mockBranches: Branch[] = [
  {
    id: "branch-001",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    name: "Greenfield Main Campus",
    code: "GEG-MC",
    address: "123 Education Avenue",
    city: "Springfield",
    state: "Illinois",
    country: "United States",
    zipCode: "62701",
    phone: "+1-555-0101",
    email: "main@greenfield.edu",
    principal: "Dr. James Wilson",
    studentCount: 6200,
    teacherCount: 420,
    departmentCount: 8,
    isActive: true,
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(1),
  },
  {
    id: "branch-002",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    name: "Greenfield South Campus",
    code: "GEG-SC",
    address: "321 South Blvd",
    city: "Springfield",
    state: "Illinois",
    country: "United States",
    zipCode: "62704",
    phone: "+1-555-0102",
    email: "south@greenfield.edu",
    principal: "Dr. Lisa Park",
    studentCount: 4200,
    teacherCount: 310,
    departmentCount: 6,
    isActive: true,
    createdAt: daysAgo(2190),
    updatedAt: daysAgo(2),
  },
  {
    id: "branch-003",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    name: "Greenfield East Campus",
    code: "GEG-EC",
    address: "654 East Road",
    city: "Decatur",
    state: "Illinois",
    country: "United States",
    zipCode: "62521",
    phone: "+1-555-0103",
    email: "east@greenfield.edu",
    studentCount: 2100,
    teacherCount: 120,
    departmentCount: 4,
    isActive: true,
    createdAt: daysAgo(1095),
    updatedAt: daysAgo(5),
  },
];

// -------------------- Departments --------------------

export const mockDepartments: Department[] = [
  {
    id: "dept-001",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "Computer Science",
    code: "CS",
    headOfDepartment: "Prof. Emily Rodriguez",
    description: "Department of Computer Science and Engineering",
    teacherCount: 35,
    studentCount: 850,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "dept-002",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "Mathematics",
    code: "MATH",
    headOfDepartment: "Prof. David Kim",
    description: "Department of Applied and Pure Mathematics",
    teacherCount: 22,
    studentCount: 420,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "dept-003",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "Business Administration",
    code: "BA",
    headOfDepartment: "Prof. Angela Foster",
    description: "School of Business and Management",
    teacherCount: 28,
    studentCount: 780,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "dept-004",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "Electrical Engineering",
    code: "EE",
    headOfDepartment: "Prof. Robert Zhang",
    description: "Department of Electrical and Electronics Engineering",
    teacherCount: 20,
    studentCount: 390,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "dept-005",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "Physics",
    code: "PHY",
    headOfDepartment: "Prof. Maria Gonzalez",
    teacherCount: 15,
    studentCount: 280,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "dept-006",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    name: "English & Humanities",
    code: "ENG",
    headOfDepartment: "Prof. Thomas Wright",
    teacherCount: 18,
    studentCount: 340,
    isActive: true,
    createdAt: daysAgo(3650),
  },
];

// -------------------- Programs --------------------

export const mockPrograms: Program[] = [
  {
    id: "prog-001",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    name: "B.Tech Computer Science",
    code: "BTech-CS",
    duration: 4,
    durationUnit: "Years",
    description: "Bachelor of Technology in Computer Science and Engineering",
    totalCredits: 160,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "prog-002",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    name: "M.Tech Computer Science",
    code: "MTech-CS",
    duration: 2,
    durationUnit: "Years",
    description: "Master of Technology in Computer Science",
    totalCredits: 80,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "prog-003",
    departmentId: "dept-002",
    departmentName: "Mathematics",
    name: "B.Sc Mathematics",
    code: "BSc-MATH",
    duration: 3,
    durationUnit: "Years",
    description: "Bachelor of Science in Mathematics",
    totalCredits: 120,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "prog-004",
    departmentId: "dept-003",
    departmentName: "Business Administration",
    name: "BBA",
    code: "BBA",
    duration: 3,
    durationUnit: "Years",
    description: "Bachelor of Business Administration",
    totalCredits: 120,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "prog-005",
    departmentId: "dept-003",
    departmentName: "Business Administration",
    name: "MBA",
    code: "MBA",
    duration: 2,
    durationUnit: "Years",
    description: "Master of Business Administration",
    totalCredits: 80,
    isActive: true,
    createdAt: daysAgo(3650),
  },
  {
    id: "prog-006",
    departmentId: "dept-004",
    departmentName: "Electrical Engineering",
    name: "B.Tech Electrical Engineering",
    code: "BTech-EE",
    duration: 4,
    durationUnit: "Years",
    description: "Bachelor of Technology in Electrical Engineering",
    totalCredits: 160,
    isActive: true,
    createdAt: daysAgo(3650),
  },
];

// -------------------- Academic Years & Terms --------------------

const currentYear = new Date().getFullYear();

export const mockAcademicYears: AcademicYear[] = [
  {
    id: "ay-001",
    branchId: "branch-001",
    name: `${currentYear - 1}-${currentYear}`,
    startDate: `${currentYear - 1}-08-01`,
    endDate: `${currentYear}-05-31`,
    currentTerm: "term-002",
    terms: [
      {
        id: "term-001",
        academicYearId: "ay-001",
        name: "Fall Semester",
        startDate: `${currentYear - 1}-08-01`,
        endDate: `${currentYear - 1}-12-20`,
        termNumber: 1,
        isActive: false,
      },
      {
        id: "term-002",
        academicYearId: "ay-001",
        name: "Spring Semester",
        startDate: `${currentYear}-01-15`,
        endDate: `${currentYear}-05-31`,
        termNumber: 2,
        isActive: true,
      },
    ],
    isActive: true,
  },
];

// -------------------- Batches --------------------

export const mockBatches: Batch[] = [
  {
    id: "batch-001",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    branchId: "branch-001",
    name: "CS 2023-27",
    code: "CS23",
    startYear: 2023,
    endYear: 2027,
    currentSemester: 4,
    studentCount: 65,
    advisorId: "u-teacher-001",
    advisorName: "Prof. Emily Rodriguez",
    isActive: true,
    createdAt: daysAgo(730),
  },
  {
    id: "batch-002",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    branchId: "branch-001",
    name: "CS 2024-28",
    code: "CS24",
    startYear: 2024,
    endYear: 2028,
    currentSemester: 2,
    studentCount: 72,
    advisorId: "u-teacher-003",
    advisorName: "Prof. Michael Lee",
    isActive: true,
    createdAt: daysAgo(365),
  },
  {
    id: "batch-003",
    programId: "prog-004",
    programName: "BBA",
    branchId: "branch-001",
    name: "BBA 2023-26",
    code: "BBA23",
    startYear: 2023,
    endYear: 2026,
    currentSemester: 4,
    studentCount: 58,
    advisorId: "u-teacher-004",
    advisorName: "Prof. Angela Foster",
    isActive: true,
    createdAt: daysAgo(730),
  },
  {
    id: "batch-004",
    programId: "prog-006",
    programName: "B.Tech Electrical Engineering",
    branchId: "branch-001",
    name: "EE 2022-26",
    code: "EE22",
    startYear: 2022,
    endYear: 2026,
    currentSemester: 6,
    studentCount: 48,
    advisorId: "u-teacher-005",
    advisorName: "Prof. Robert Zhang",
    isActive: true,
    createdAt: daysAgo(1095),
  },
];

// -------------------- Users --------------------

export const mockStudents: Student[] = [
  {
    id: "u-student-001",
    name: "Ryan Patel",
    email: "ryan.patel@student.campus.edu",
    phone: "+1-555-1001",
    role: "Student",
    gender: "Male",
    dateOfBirth: "2004-05-15",
    address: "42 Oak Street, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "CS20230101",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    semester: 4,
    enrollmentDate: "2023-08-01",
    guardianName: "Meera Patel",
    guardianPhone: "+1-555-2001",
    guardianEmail: "meera.patel@email.com",
    parentIds: ["u-parent-001"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-student-002",
    name: "Sophia Martinez",
    email: "sophia.martinez@student.campus.edu",
    phone: "+1-555-1002",
    role: "Student",
    gender: "Female",
    dateOfBirth: "2004-08-22",
    address: "15 Maple Drive, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "CS20230102",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    semester: 4,
    enrollmentDate: "2023-08-01",
    guardianName: "Carlos Martinez",
    guardianPhone: "+1-555-2002",
    parentIds: ["u-parent-002"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(1),
  },
  {
    id: "u-student-003",
    name: "Liam Johnson",
    email: "liam.johnson@student.campus.edu",
    phone: "+1-555-1003",
    role: "Student",
    gender: "Male",
    dateOfBirth: "2004-03-10",
    address: "88 Pine Road, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "CS20230103",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    semester: 4,
    enrollmentDate: "2023-08-01",
    guardianName: "Mark Johnson",
    guardianPhone: "+1-555-2003",
    parentIds: ["u-parent-003"],
    lastLogin: daysAgo(1),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(1),
  },
  {
    id: "u-student-004",
    name: "Emma Thompson",
    email: "emma.thompson@student.campus.edu",
    phone: "+1-555-1004",
    role: "Student",
    gender: "Female",
    dateOfBirth: "2004-11-05",
    address: "22 Cedar Lane, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "CS20230104",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    semester: 4,
    enrollmentDate: "2023-08-01",
    guardianName: "David Thompson",
    guardianPhone: "+1-555-2004",
    parentIds: ["u-parent-004"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-student-005",
    name: "Noah Williams",
    email: "noah.williams@student.campus.edu",
    phone: "+1-555-1005",
    role: "Student",
    gender: "Male",
    dateOfBirth: "2004-01-20",
    address: "56 Birch Avenue, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "BBA20230101",
    batchId: "batch-003",
    batchName: "BBA 2023-26",
    programId: "prog-004",
    programName: "BBA",
    departmentId: "dept-003",
    departmentName: "Business Administration",
    semester: 4,
    enrollmentDate: "2023-08-01",
    guardianName: "Karen Williams",
    guardianPhone: "+1-555-2005",
    parentIds: ["u-parent-005"],
    lastLogin: daysAgo(2),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(2),
  },
  {
    id: "u-student-006",
    name: "Ava Chen",
    email: "ava.chen@student.campus.edu",
    phone: "+1-555-1006",
    role: "Student",
    gender: "Female",
    dateOfBirth: "2004-07-18",
    address: "33 Elm Court, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    rollNumber: "EE20220101",
    batchId: "batch-004",
    batchName: "EE 2022-26",
    programId: "prog-006",
    programName: "B.Tech Electrical Engineering",
    departmentId: "dept-004",
    departmentName: "Electrical Engineering",
    semester: 6,
    enrollmentDate: "2022-08-01",
    guardianName: "Wei Chen",
    guardianPhone: "+1-555-2006",
    parentIds: ["u-parent-006"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(1095),
    updatedAt: daysAgo(0),
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: "u-teacher-001",
    name: "Prof. Emily Rodriguez",
    email: "emily.rodriguez@campus.edu",
    phone: "+1-555-3001",
    role: "Teacher",
    gender: "Female",
    dateOfBirth: "1985-04-12",
    address: "101 Faculty Row, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    employeeId: "T20180101",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    designation: "Associate Professor",
    specialization: ["Data Structures", "Algorithms", "Machine Learning"],
    qualification: "Ph.D. Computer Science",
    joinDate: "2018-07-01",
    subjects: ["Data Structures", "Algorithms", "Machine Learning"],
    batchIds: ["batch-001", "batch-002"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(2555),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-teacher-002",
    name: "Prof. David Kim",
    email: "david.kim@campus.edu",
    phone: "+1-555-3002",
    role: "Teacher",
    gender: "Male",
    dateOfBirth: "1980-09-28",
    address: "102 Faculty Row, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    employeeId: "T20150102",
    departmentId: "dept-002",
    departmentName: "Mathematics",
    designation: "Professor",
    specialization: ["Linear Algebra", "Calculus", "Statistics"],
    qualification: "Ph.D. Mathematics",
    joinDate: "2015-07-01",
    subjects: ["Linear Algebra", "Engineering Mathematics"],
    batchIds: ["batch-001", "batch-003"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-teacher-003",
    name: "Prof. Michael Lee",
    email: "michael.lee@campus.edu",
    phone: "+1-555-3003",
    role: "Teacher",
    gender: "Male",
    dateOfBirth: "1988-02-14",
    address: "103 Faculty Row, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    employeeId: "T20200103",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    designation: "Assistant Professor",
    specialization: ["Database Systems", "Software Engineering", "Web Development"],
    qualification: "M.Tech Computer Science",
    joinDate: "2020-07-01",
    subjects: ["Database Systems", "Software Engineering"],
    batchIds: ["batch-002"],
    lastLogin: daysAgo(1),
    createdAt: daysAgo(1825),
    updatedAt: daysAgo(1),
  },
  {
    id: "u-teacher-004",
    name: "Prof. Angela Foster",
    email: "angela.foster@campus.edu",
    phone: "+1-555-3004",
    role: "Teacher",
    gender: "Female",
    dateOfBirth: "1982-12-03",
    address: "104 Faculty Row, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    employeeId: "T20160104",
    departmentId: "dept-003",
    departmentName: "Business Administration",
    designation: "Professor",
    specialization: ["Marketing", "Strategic Management", "Entrepreneurship"],
    qualification: "MBA, Ph.D. Management",
    joinDate: "2016-07-01",
    subjects: ["Marketing Management", "Strategic Management"],
    batchIds: ["batch-003"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(3285),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-teacher-005",
    name: "Prof. Robert Zhang",
    email: "robert.zhang@campus.edu",
    phone: "+1-555-3005",
    role: "Teacher",
    gender: "Male",
    dateOfBirth: "1978-06-22",
    address: "105 Faculty Row, Springfield",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    employeeId: "T20120105",
    departmentId: "dept-004",
    departmentName: "Electrical Engineering",
    designation: "Professor",
    specialization: ["Power Systems", "Control Systems", "Circuits"],
    qualification: "Ph.D. Electrical Engineering",
    joinDate: "2012-07-01",
    subjects: ["Power Systems", "Control Systems"],
    batchIds: ["batch-004"],
    lastLogin: daysAgo(0),
    createdAt: daysAgo(4745),
    updatedAt: daysAgo(0),
  },
];

export const mockParents: Parent[] = [
  {
    id: "u-parent-001",
    name: "Meera Patel",
    email: "meera.patel@email.com",
    phone: "+1-555-2001",
    role: "Parent",
    gender: "Female",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    childrenIds: ["u-student-001"],
    children: [mockStudents[0]],
    occupation: "Software Engineer",
    lastLogin: daysAgo(0),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-parent-002",
    name: "Carlos Martinez",
    email: "carlos.martinez@email.com",
    phone: "+1-555-2002",
    role: "Parent",
    gender: "Male",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    childrenIds: ["u-student-002"],
    children: [mockStudents[1]],
    occupation: "Business Owner",
    lastLogin: daysAgo(2),
    createdAt: daysAgo(730),
    updatedAt: daysAgo(2),
  },
];

export const mockAdminUsers: User[] = [
  {
    id: "u-super-001",
    name: "Alex Morgan",
    email: "alex.morgan@campus.edu",
    phone: "+1-555-0001",
    role: "SuperAdmin",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-inst-001",
    name: "Dr. Sarah Chen",
    email: "sarah.chen@campus.edu",
    phone: "+1-555-0002",
    role: "InstituteAdmin",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(0),
  },
  {
    id: "u-branch-001",
    name: "James Wilson",
    email: "james.wilson@campus.edu",
    phone: "+1-555-0003",
    role: "BranchAdmin",
    instituteId: "inst-001",
    instituteName: "Greenfield Education Group",
    branchId: "branch-001",
    branchName: "Greenfield Main Campus",
    isActive: true,
    lastLogin: daysAgo(0),
    createdAt: daysAgo(3650),
    updatedAt: daysAgo(0),
  },
];

// -------------------- Courses --------------------

export const mockCourseModules: CourseModule[] = [
  {
    id: "mod-001",
    courseId: "course-001",
    title: "Introduction to Data Structures",
    description: "Fundamentals of data structures including arrays, linked lists, stacks, and queues",
    order: 1,
    lessons: [
      { id: "lesson-001", moduleId: "mod-001", title: "Arrays and Memory", description: "Understanding array storage", contentType: "Video", duration: 45, order: 1, isCompleted: true, createdAt: daysAgo(120) },
      { id: "lesson-002", moduleId: "mod-001", title: "Linked Lists", description: "Singly and doubly linked lists", contentType: "Video", duration: 60, order: 2, isCompleted: true, createdAt: daysAgo(115) },
      { id: "lesson-003", moduleId: "mod-001", title: "Stacks and Queues", description: "LIFO and FIFO structures", contentType: "Video", duration: 50, order: 3, isCompleted: false, createdAt: daysAgo(110) },
      { id: "lesson-004", moduleId: "mod-001", title: "Module 1 Practice", description: "Practice problems", contentType: "Link", order: 4, isCompleted: false, createdAt: daysAgo(110) },
    ],
    createdAt: daysAgo(120),
  },
  {
    id: "mod-002",
    courseId: "course-001",
    title: "Trees and Graphs",
    description: "Tree structures, binary trees, BST, and graph representations",
    order: 2,
    lessons: [
      { id: "lesson-005", moduleId: "mod-002", title: "Binary Trees", description: "Tree fundamentals", contentType: "Video", duration: 55, order: 1, isCompleted: false, createdAt: daysAgo(90) },
      { id: "lesson-006", moduleId: "mod-002", title: "Graph Theory Basics", description: "Graph representations and traversal", contentType: "Video", duration: 65, order: 2, isCompleted: false, createdAt: daysAgo(85) },
    ],
    createdAt: daysAgo(90),
  },
];

export const mockCourses: Course[] = [
  {
    id: "course-001",
    code: "CS201",
    name: "Data Structures & Algorithms",
    description: "Comprehensive study of data structures, algorithm design, and analysis techniques",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    credits: 4,
    semester: 4,
    totalHours: 48,
    modules: mockCourseModules,
    enrolledCount: 65,
    maxCapacity: 70,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "course-002",
    code: "CS202",
    name: "Database Management Systems",
    description: "Relational database design, SQL, normalization, and transaction management",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    teacherId: "u-teacher-003",
    teacherName: "Prof. Michael Lee",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    credits: 4,
    semester: 4,
    totalHours: 48,
    modules: [],
    enrolledCount: 65,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "course-003",
    code: "MATH301",
    name: "Linear Algebra",
    description: "Vector spaces, linear transformations, eigenvalues, and matrix theory",
    departmentId: "dept-002",
    departmentName: "Mathematics",
    teacherId: "u-teacher-002",
    teacherName: "Prof. David Kim",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    credits: 3,
    semester: 4,
    totalHours: 36,
    modules: [],
    enrolledCount: 65,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "course-004",
    code: "BA301",
    name: "Marketing Management",
    description: "Principles of marketing, consumer behavior, and market strategy",
    departmentId: "dept-003",
    departmentName: "Business Administration",
    teacherId: "u-teacher-004",
    teacherName: "Prof. Angela Foster",
    programId: "prog-004",
    programName: "BBA",
    batchId: "batch-003",
    batchName: "BBA 2023-26",
    credits: 3,
    semester: 4,
    totalHours: 36,
    modules: [],
    enrolledCount: 58,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "course-005",
    code: "EE401",
    name: "Power Systems Engineering",
    description: "Generation, transmission, and distribution of electric power",
    departmentId: "dept-004",
    departmentName: "Electrical Engineering",
    teacherId: "u-teacher-005",
    teacherName: "Prof. Robert Zhang",
    programId: "prog-006",
    programName: "B.Tech Electrical Engineering",
    batchId: "batch-004",
    batchName: "EE 2022-26",
    credits: 4,
    semester: 6,
    totalHours: 48,
    modules: [],
    enrolledCount: 48,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "course-006",
    code: "CS301",
    name: "Machine Learning",
    description: "Supervised and unsupervised learning, neural networks, and deep learning fundamentals",
    departmentId: "dept-001",
    departmentName: "Computer Science",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    programId: "prog-001",
    programName: "B.Tech Computer Science",
    batchId: "batch-002",
    batchName: "CS 2024-28",
    credits: 3,
    semester: 2,
    totalHours: 36,
    modules: [],
    enrolledCount: 72,
    startDate: `${currentYear}-01-15`,
    endDate: `${currentYear}-05-15`,
    isActive: true,
    createdAt: daysAgo(90),
  },
];

// -------------------- Enrollments --------------------

export const mockEnrollments: Enrollment[] = [
  { id: "enr-001", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 92 },
  { id: "enr-002", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-002", courseName: "Database Management Systems", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 88 },
  { id: "enr-003", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-003", courseName: "Linear Algebra", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 95 },
  { id: "enr-004", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 97 },
  { id: "enr-005", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-002", courseName: "Database Management Systems", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 94 },
  { id: "enr-006", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 78 },
  { id: "enr-007", studentId: "u-student-004", studentName: "Emma Thompson", courseId: "course-001", courseName: "Data Structures & Algorithms", batchId: "batch-001", batchName: "CS 2023-27", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 91 },
  { id: "enr-008", studentId: "u-student-005", studentName: "Noah Williams", courseId: "course-004", courseName: "Marketing Management", batchId: "batch-003", batchName: "BBA 2023-26", enrolledDate: "2023-08-01", status: "Active", attendancePercentage: 85 },
];

// -------------------- Attendance --------------------

export const mockAttendanceSessions: AttendanceSession[] = [
  {
    id: "att-session-001",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    date: daysAgo(0).split("T")[0],
    startTime: "09:00",
    endTime: "10:30",
    totalStudents: 65,
    presentCount: 58,
    absentCount: 4,
    lateCount: 2,
    excusedCount: 1,
    isCompleted: true,
    createdAt: daysAgo(0),
  },
  {
    id: "att-session-002",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    date: daysAgo(2).split("T")[0],
    startTime: "09:00",
    endTime: "10:30",
    totalStudents: 65,
    presentCount: 60,
    absentCount: 3,
    lateCount: 1,
    excusedCount: 1,
    isCompleted: true,
    createdAt: daysAgo(2),
  },
  {
    id: "att-session-003",
    courseId: "course-002",
    courseName: "Database Management Systems",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-003",
    teacherName: "Prof. Michael Lee",
    date: daysAgo(1).split("T")[0],
    startTime: "11:00",
    endTime: "12:30",
    totalStudents: 65,
    presentCount: 55,
    absentCount: 7,
    lateCount: 2,
    excusedCount: 1,
    isCompleted: true,
    createdAt: daysAgo(1),
  },
  {
    id: "att-session-004",
    courseId: "course-003",
    courseName: "Linear Algebra",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-002",
    teacherName: "Prof. David Kim",
    date: daysAgo(1).split("T")[0],
    startTime: "14:00",
    endTime: "15:30",
    totalStudents: 65,
    presentCount: 62,
    absentCount: 2,
    lateCount: 1,
    excusedCount: 0,
    isCompleted: true,
    createdAt: daysAgo(1),
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: "att-001", sessionId: "att-session-001", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(0).split("T")[0], status: "Present", markedBy: "u-teacher-001", markedAt: daysAgo(0) },
  { id: "att-002", sessionId: "att-session-001", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(0).split("T")[0], status: "Present", markedBy: "u-teacher-001", markedAt: daysAgo(0) },
  { id: "att-003", sessionId: "att-session-001", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(0).split("T")[0], status: "Late", markedBy: "u-teacher-001", markedAt: daysAgo(0) },
  { id: "att-004", sessionId: "att-session-001", studentId: "u-student-004", studentName: "Emma Thompson", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(0).split("T")[0], status: "Present", markedBy: "u-teacher-001", markedAt: daysAgo(0) },
  { id: "att-005", sessionId: "att-session-002", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(2).split("T")[0], status: "Present", markedBy: "u-teacher-001", markedAt: daysAgo(2) },
  { id: "att-006", sessionId: "att-session-002", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(2).split("T")[0], status: "Present", markedBy: "u-teacher-001", markedAt: daysAgo(2) },
  { id: "att-007", sessionId: "att-session-002", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", date: daysAgo(2).split("T")[0], status: "Absent", markedBy: "u-teacher-001", markedAt: daysAgo(2) },
  { id: "att-008", sessionId: "att-session-003", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-002", courseName: "Database Management Systems", date: daysAgo(1).split("T")[0], status: "Present", markedBy: "u-teacher-003", markedAt: daysAgo(1) },
  { id: "att-009", sessionId: "att-session-003", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-002", courseName: "Database Management Systems", date: daysAgo(1).split("T")[0], status: "Present", markedBy: "u-teacher-003", markedAt: daysAgo(1) },
  { id: "att-010", sessionId: "att-session-003", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-002", courseName: "Database Management Systems", date: daysAgo(1).split("T")[0], status: "Absent", remarks: "Medical leave", markedBy: "u-teacher-003", markedAt: daysAgo(1) },
];

// -------------------- Assignments --------------------

export const mockAssignments: Assignment[] = [
  {
    id: "asgn-001",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    title: "Binary Search Tree Implementation",
    description: "Implement a BST with insertion, deletion, search, and traversal methods. Include test cases and complexity analysis.",
    type: "Homework",
    totalMarks: 100,
    dueDate: daysFromNow(5).split("T")[0],
    allowLateSubmission: true,
    latePenalty: 10,
    submissionsCount: 42,
    totalStudents: 65,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "asgn-002",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    title: "Graph Traversal Algorithms",
    description: "Implement BFS and DFS for weighted and unweighted graphs. Compare time complexities.",
    type: "Lab",
    totalMarks: 50,
    dueDate: daysFromNow(10).split("T")[0],
    allowLateSubmission: false,
    submissionsCount: 28,
    totalStudents: 65,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "asgn-003",
    courseId: "course-002",
    courseName: "Database Management Systems",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-003",
    teacherName: "Prof. Michael Lee",
    title: "ER Diagram & Schema Design",
    description: "Design an ER diagram for a university management system and create the corresponding relational schema with proper normalization.",
    type: "Project",
    totalMarks: 100,
    dueDate: daysAgo(2).split("T")[0],
    allowLateSubmission: true,
    latePenalty: 5,
    submissionsCount: 61,
    totalStudents: 65,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(0),
  },
  {
    id: "asgn-004",
    courseId: "course-003",
    courseName: "Linear Algebra",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-002",
    teacherName: "Prof. David Kim",
    title: "Eigenvalue Problem Set",
    description: "Solve problems on eigenvalues, eigenvectors, and diagonalization of matrices.",
    type: "Homework",
    totalMarks: 50,
    dueDate: daysFromNow(3).split("T")[0],
    allowLateSubmission: true,
    latePenalty: 15,
    submissionsCount: 30,
    totalStudents: 65,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "asgn-005",
    courseId: "course-004",
    courseName: "Marketing Management",
    batchId: "batch-003",
    batchName: "BBA 2023-26",
    teacherId: "u-teacher-004",
    teacherName: "Prof. Angela Foster",
    title: "Marketing Plan Presentation",
    description: "Create a comprehensive marketing plan for a new product launch. Present with market analysis, segmentation, and strategy.",
    type: "Presentation",
    totalMarks: 100,
    dueDate: daysFromNow(14).split("T")[0],
    allowLateSubmission: false,
    submissionsCount: 15,
    totalStudents: 58,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },
];

export const mockSubmissions: Submission[] = [
  { id: "sub-001", assignmentId: "asgn-001", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", status: "Submitted", submittedAt: daysAgo(1), createdAt: daysAgo(1) },
  { id: "sub-002", assignmentId: "asgn-001", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", status: "Graded", submittedAt: daysAgo(2), marksObtained: 92, feedback: "Excellent implementation! Great test coverage.", gradedBy: "u-teacher-001", gradedAt: daysAgo(0), createdAt: daysAgo(2) },
  { id: "sub-003", assignmentId: "asgn-001", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", status: "NotSubmitted", createdAt: daysAgo(10) },
  { id: "sub-004", assignmentId: "asgn-003", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-002", courseName: "Database Management Systems", status: "Graded", submittedAt: daysAgo(3), marksObtained: 88, feedback: "Good schema design. Minor issues in normalization.", gradedBy: "u-teacher-003", gradedAt: daysAgo(1), createdAt: daysAgo(3) },
  { id: "sub-005", assignmentId: "asgn-003", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-002", courseName: "Database Management Systems", status: "Graded", submittedAt: daysAgo(4), marksObtained: 95, feedback: "Outstanding work! Perfect normalization.", gradedBy: "u-teacher-003", gradedAt: daysAgo(1), createdAt: daysAgo(4) },
  { id: "sub-006", assignmentId: "asgn-003", studentId: "u-student-004", studentName: "Emma Thompson", courseId: "course-002", courseName: "Database Management Systems", status: "Graded", submittedAt: daysAgo(5), marksObtained: 78, feedback: "Decent attempt. Review the 3NF requirements.", gradedBy: "u-teacher-003", gradedAt: daysAgo(0), createdAt: daysAgo(5) },
];

// -------------------- Assessments --------------------

export const mockAssessments: Assessment[] = [
  {
    id: "assess-001",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    title: "Midterm Examination",
    type: "Exam",
    totalMarks: 100,
    passingMarks: 40,
    weightage: 30,
    date: daysAgo(30).split("T")[0],
    duration: 180,
    questionsCount: 25,
    isActive: false,
    createdAt: daysAgo(45),
  },
  {
    id: "assess-002",
    courseId: "course-001",
    courseName: "Data Structures & Algorithms",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-001",
    teacherName: "Prof. Emily Rodriguez",
    title: "Quiz 3: Trees & Graphs",
    type: "Quiz",
    totalMarks: 20,
    passingMarks: 8,
    weightage: 10,
    date: daysFromNow(7).split("T")[0],
    duration: 30,
    questionsCount: 10,
    isActive: true,
    createdAt: daysAgo(5),
  },
  {
    id: "assess-003",
    courseId: "course-002",
    courseName: "Database Management Systems",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-003",
    teacherName: "Prof. Michael Lee",
    title: "Midterm Examination",
    type: "Exam",
    totalMarks: 100,
    passingMarks: 40,
    weightage: 30,
    date: daysAgo(25).split("T")[0],
    duration: 150,
    questionsCount: 20,
    isActive: false,
    createdAt: daysAgo(40),
  },
  {
    id: "assess-004",
    courseId: "course-003",
    courseName: "Linear Algebra",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    teacherId: "u-teacher-002",
    teacherName: "Prof. David Kim",
    title: "Midterm Examination",
    type: "Exam",
    totalMarks: 100,
    passingMarks: 35,
    weightage: 30,
    date: daysAgo(20).split("T")[0],
    duration: 120,
    questionsCount: 15,
    isActive: false,
    createdAt: daysAgo(35),
  },
];

export const mockQuizAttempts: QuizAttempt[] = [
  { id: "qa-001", assessmentId: "assess-001", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", score: 78, totalMarks: 100, percentage: 78, timeSpent: 150, startedAt: daysAgo(30), submittedAt: daysAgo(30), isCompleted: true },
  { id: "qa-002", assessmentId: "assess-001", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", score: 91, totalMarks: 100, percentage: 91, timeSpent: 140, startedAt: daysAgo(30), submittedAt: daysAgo(30), isCompleted: true },
  { id: "qa-003", assessmentId: "assess-001", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", score: 55, totalMarks: 100, percentage: 55, timeSpent: 170, startedAt: daysAgo(30), submittedAt: daysAgo(30), isCompleted: true },
  { id: "qa-004", assessmentId: "assess-003", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-002", courseName: "Database Management Systems", score: 82, totalMarks: 100, percentage: 82, timeSpent: 130, startedAt: daysAgo(25), submittedAt: daysAgo(25), isCompleted: true },
  { id: "qa-005", assessmentId: "assess-004", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-003", courseName: "Linear Algebra", score: 88, totalMarks: 100, percentage: 88, timeSpent: 100, startedAt: daysAgo(20), submittedAt: daysAgo(20), isCompleted: true },
];

// -------------------- Grades --------------------

export const mockGrades: Grade[] = [
  { id: "grade-001", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-001", courseName: "Data Structures & Algorithms", assessmentId: "assess-001", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 78, totalMarks: 100, gradePoint: 3.3, letterGrade: "B+", comments: "Good performance", gradedBy: "u-teacher-001", gradedAt: daysAgo(28) },
  { id: "grade-002", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-001", courseName: "Data Structures & Algorithms", assessmentId: "assess-001", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 91, totalMarks: 100, gradePoint: 4.0, letterGrade: "A+", comments: "Outstanding performance", gradedBy: "u-teacher-001", gradedAt: daysAgo(28) },
  { id: "grade-003", studentId: "u-student-003", studentName: "Liam Johnson", courseId: "course-001", courseName: "Data Structures & Algorithms", assessmentId: "assess-001", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 55, totalMarks: 100, gradePoint: 2.0, letterGrade: "C", comments: "Needs improvement", gradedBy: "u-teacher-001", gradedAt: daysAgo(28) },
  { id: "grade-004", studentId: "u-student-004", studentName: "Emma Thompson", courseId: "course-001", courseName: "Data Structures & Algorithms", assessmentId: "assess-001", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 83, totalMarks: 100, gradePoint: 3.7, letterGrade: "A-", comments: "Very good work", gradedBy: "u-teacher-001", gradedAt: daysAgo(28) },
  { id: "grade-005", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-002", courseName: "Database Management Systems", assessmentId: "assess-003", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 82, totalMarks: 100, gradePoint: 3.5, letterGrade: "A-", comments: "Good understanding of concepts", gradedBy: "u-teacher-003", gradedAt: daysAgo(23) },
  { id: "grade-006", studentId: "u-student-002", studentName: "Sophia Martinez", courseId: "course-002", courseName: "Database Management Systems", assessmentId: "assess-003", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 96, totalMarks: 100, gradePoint: 4.0, letterGrade: "A+", comments: "Excellent!", gradedBy: "u-teacher-003", gradedAt: daysAgo(23) },
  { id: "grade-007", studentId: "u-student-001", studentName: "Ryan Patel", courseId: "course-003", courseName: "Linear Algebra", assessmentId: "assess-004", assessmentName: "Midterm Examination", batchId: "batch-001", batchName: "CS 2023-27", semester: 4, marksObtained: 88, totalMarks: 100, gradePoint: 3.8, letterGrade: "A", comments: "Strong analytical skills", gradedBy: "u-teacher-002", gradedAt: daysAgo(18) },
];

// -------------------- Timetable --------------------

export const mockTimetable: TimetableSlot[] = [
  { id: "tt-001", courseId: "course-001", courseName: "Data Structures & Algorithms", courseCode: "CS201", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-001", teacherName: "Prof. Emily Rodriguez", roomId: "room-101", roomName: "Lecture Hall A", day: "Monday", startTime: "09:00", endTime: "10:30", color: "#10b981" },
  { id: "tt-002", courseId: "course-002", courseName: "Database Management Systems", courseCode: "CS202", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-003", teacherName: "Prof. Michael Lee", roomId: "room-102", roomName: "Lab 1", day: "Monday", startTime: "11:00", endTime: "12:30", color: "#8b5cf6" },
  { id: "tt-003", courseId: "course-003", courseName: "Linear Algebra", courseCode: "MATH301", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-002", teacherName: "Prof. David Kim", roomId: "room-103", roomName: "Room 301", day: "Monday", startTime: "14:00", endTime: "15:30", color: "#f59e0b" },
  { id: "tt-004", courseId: "course-001", courseName: "Data Structures & Algorithms", courseCode: "CS201", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-001", teacherName: "Prof. Emily Rodriguez", roomId: "room-101", roomName: "Lecture Hall A", day: "Tuesday", startTime: "09:00", endTime: "10:30", color: "#10b981" },
  { id: "tt-005", courseId: "course-004", courseName: "Marketing Management", courseCode: "BA301", batchId: "batch-003", batchName: "BBA 2023-26", teacherId: "u-teacher-004", teacherName: "Prof. Angela Foster", roomId: "room-104", roomName: "Lecture Hall B", day: "Tuesday", startTime: "11:00", endTime: "12:30", color: "#ec4899" },
  { id: "tt-006", courseId: "course-002", courseName: "Database Management Systems", courseCode: "CS202", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-003", teacherName: "Prof. Michael Lee", roomId: "room-102", roomName: "Lab 1", day: "Wednesday", startTime: "09:00", endTime: "10:30", color: "#8b5cf6" },
  { id: "tt-007", courseId: "course-001", courseName: "Data Structures & Algorithms", courseCode: "CS201", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-001", teacherName: "Prof. Emily Rodriguez", roomId: "room-101", roomName: "Lecture Hall A", day: "Wednesday", startTime: "14:00", endTime: "15:30", color: "#10b981" },
  { id: "tt-008", courseId: "course-003", courseName: "Linear Algebra", courseCode: "MATH301", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-002", teacherName: "Prof. David Kim", roomId: "room-103", roomName: "Room 301", day: "Thursday", startTime: "09:00", endTime: "10:30", color: "#f59e0b" },
  { id: "tt-009", courseId: "course-005", courseName: "Power Systems Engineering", courseCode: "EE401", batchId: "batch-004", batchName: "EE 2022-26", teacherId: "u-teacher-005", teacherName: "Prof. Robert Zhang", roomId: "room-105", roomName: "Lecture Hall C", day: "Thursday", startTime: "11:00", endTime: "12:30", color: "#06b6d4" },
  { id: "tt-010", courseId: "course-001", courseName: "Data Structures & Algorithms", courseCode: "CS201", batchId: "batch-001", batchName: "CS 2023-27", teacherId: "u-teacher-001", teacherName: "Prof. Emily Rodriguez", roomId: "room-102", roomName: "Lab 1", day: "Friday", startTime: "09:00", endTime: "11:00", color: "#10b981" },
  { id: "tt-011", courseId: "course-004", courseName: "Marketing Management", courseCode: "BA301", batchId: "batch-003", batchName: "BBA 2023-26", teacherId: "u-teacher-004", teacherName: "Prof. Angela Foster", roomId: "room-104", roomName: "Lecture Hall B", day: "Friday", startTime: "14:00", endTime: "15:30", color: "#ec4899" },
];

// -------------------- Fee Data --------------------

export const mockFeeInvoices: FeeInvoice[] = [
  {
    id: "fee-001",
    studentId: "u-student-001",
    studentName: "Ryan Patel",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    invoiceNumber: "INV-2024-001",
    amount: 15000,
    discount: 1500,
    tax: 750,
    totalAmount: 14250,
    paidAmount: 14250,
    balanceAmount: 0,
    status: "Paid",
    dueDate: `${currentYear}-01-31`,
    issuedDate: `${currentYear}-01-01`,
    description: "Spring Semester 2025 Tuition Fee",
    payments: [
      { id: "pay-001", invoiceId: "fee-001", studentId: "u-student-001", amount: 14250, method: "Bank Transfer", transactionId: "TXN-2024-001", receiptNumber: "RCP-001", paymentDate: `${currentYear}-01-15`, status: "Success" },
    ],
    createdAt: daysAgo(60),
  },
  {
    id: "fee-002",
    studentId: "u-student-001",
    studentName: "Ryan Patel",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    invoiceNumber: "INV-2024-002",
    amount: 8000,
    totalAmount: 8000,
    paidAmount: 0,
    balanceAmount: 8000,
    status: "Pending",
    dueDate: daysFromNow(15).split("T")[0],
    issuedDate: daysAgo(5).split("T")[0],
    description: "Lab & Equipment Fee - Spring 2025",
    payments: [],
    createdAt: daysAgo(5),
  },
  {
    id: "fee-003",
    studentId: "u-student-002",
    studentName: "Sophia Martinez",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    invoiceNumber: "INV-2024-003",
    amount: 15000,
    discount: 2000,
    tax: 650,
    totalAmount: 13650,
    paidAmount: 13650,
    balanceAmount: 0,
    status: "Paid",
    dueDate: `${currentYear}-01-31`,
    issuedDate: `${currentYear}-01-01`,
    description: "Spring Semester 2025 Tuition Fee",
    payments: [
      { id: "pay-002", invoiceId: "fee-003", studentId: "u-student-002", amount: 13650, method: "Online", transactionId: "TXN-2024-002", receiptNumber: "RCP-002", paymentDate: `${currentYear}-01-10`, status: "Success" },
    ],
    createdAt: daysAgo(60),
  },
  {
    id: "fee-004",
    studentId: "u-student-003",
    studentName: "Liam Johnson",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    invoiceNumber: "INV-2024-004",
    amount: 15000,
    tax: 750,
    totalAmount: 15750,
    paidAmount: 5000,
    balanceAmount: 10750,
    status: "Partial",
    dueDate: daysAgo(10).split("T")[0],
    issuedDate: daysAgo(45).split("T")[0],
    description: "Spring Semester 2025 Tuition Fee",
    payments: [
      { id: "pay-003", invoiceId: "fee-004", studentId: "u-student-003", amount: 5000, method: "Cash", receiptNumber: "RCP-003", paymentDate: daysAgo(30).split("T")[0], status: "Success" },
    ],
    createdAt: daysAgo(45),
  },
  {
    id: "fee-005",
    studentId: "u-student-005",
    studentName: "Noah Williams",
    batchId: "batch-003",
    batchName: "BBA 2023-26",
    invoiceNumber: "INV-2024-005",
    amount: 12000,
    tax: 600,
    totalAmount: 12600,
    paidAmount: 0,
    balanceAmount: 12600,
    status: "Overdue",
    dueDate: daysAgo(15).split("T")[0],
    issuedDate: daysAgo(60).split("T")[0],
    description: "Spring Semester 2025 Tuition Fee",
    payments: [],
    createdAt: daysAgo(60),
  },
];

// -------------------- Announcements --------------------

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-001",
    title: "Spring Semester Examination Schedule Released",
    content: "The final examination schedule for Spring Semester 2025 has been released. Please check your individual timetable on the student portal. Examinations will commence from May 15, 2025. Students are advised to collect their hall tickets from the examination cell.",
    authorId: "u-branch-001",
    authorName: "James Wilson",
    authorRole: "BranchAdmin",
    targetAudience: ["Student", "Teacher"],
    targetBranches: ["branch-001"],
    isImportant: true,
    viewsCount: 2450,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    expiresAt: daysFromNow(30).split("T")[0],
  },
  {
    id: "ann-002",
    title: "Annual Sports Day - Registration Open",
    content: "Registration for the Annual Sports Day 2025 is now open. Events include athletics, basketball, volleyball, chess, and more. Register before April 30th at the Sports Office. All students and faculty members are encouraged to participate.",
    authorId: "u-teacher-004",
    authorName: "Prof. Angela Foster",
    authorRole: "Teacher",
    targetAudience: ["Student", "Teacher", "Parent"],
    targetBranches: ["branch-001"],
    isImportant: false,
    viewsCount: 1200,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
    expiresAt: daysFromNow(20).split("T")[0],
  },
  {
    id: "ann-003",
    title: "Campus Maintenance Notice - Library Renovation",
    content: "The central library will undergo renovation from April 20 to May 5, 2025. During this period, students can access the digital library and e-resources online. The temporary reading room will be set up in Block C, Room 201.",
    authorId: "u-branch-001",
    authorName: "James Wilson",
    authorRole: "BranchAdmin",
    targetAudience: ["Student", "Teacher"],
    targetBranches: ["branch-001"],
    isImportant: true,
    viewsCount: 890,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    expiresAt: daysFromNow(15).split("T")[0],
  },
  {
    id: "ann-004",
    title: "Fee Payment Deadline Extended",
    content: "The fee payment deadline for Spring Semester 2025 has been extended to April 25, 2025. Students with overdue payments are requested to clear their dues at the earliest to avoid late fees. Payment can be made online through the student portal or at the accounts office.",
    authorId: "u-inst-001",
    authorName: "Dr. Sarah Chen",
    authorRole: "InstituteAdmin",
    targetAudience: ["Student", "Parent"],
    isImportant: true,
    viewsCount: 3400,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    expiresAt: daysFromNow(12).split("T")[0],
  },
  {
    id: "ann-005",
    title: "New Course: Introduction to AI & Ethics",
    content: "We are pleased to announce a new elective course 'Introduction to AI & Ethics' available for all branches starting next semester. This interdisciplinary course covers the ethical implications of artificial intelligence, bias in algorithms, and responsible AI development.",
    authorId: "u-teacher-001",
    authorName: "Prof. Emily Rodriguez",
    authorRole: "Teacher",
    targetAudience: ["Student"],
    targetBranches: ["branch-001"],
    isImportant: false,
    viewsCount: 670,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// -------------------- Notifications --------------------

export const mockNotifications: Notification[] = [
  { id: "notif-001", userId: "u-student-001", title: "Assignment Due Tomorrow", message: "Your 'Binary Search Tree Implementation' assignment is due tomorrow. Make sure to submit on time.", type: "Warning", link: "assignments", isRead: false, createdAt: daysAgo(0) },
  { id: "notif-002", userId: "u-student-001", title: "Grade Published", message: "Your midterm examination grade for Data Structures & Algorithms has been published. You scored B+.", type: "Success", link: "grades", isRead: false, createdAt: daysAgo(1) },
  { id: "notif-003", userId: "u-student-001", title: "Fee Reminder", message: "Your lab and equipment fee of $8,000 is due in 15 days. Please clear your dues on time.", type: "Warning", link: "fees", isRead: false, createdAt: daysAgo(2) },
  { id: "notif-004", userId: "u-student-001", title: "New Announcement", message: "Spring Semester Examination Schedule has been released.", type: "Announcement", link: "announcements", isRead: true, createdAt: daysAgo(3) },
  { id: "notif-005", userId: "u-student-001", title: "Attendance Updated", message: "Your attendance for today's Data Structures class has been marked as Present.", type: "Info", link: "attendance", isRead: true, createdAt: daysAgo(0) },
  { id: "notif-006", userId: "u-student-001", title: "Message from Prof. Rodriguez", message: "Please come to my office during office hours to discuss your project proposal.", type: "Info", link: "messages", isRead: false, createdAt: daysAgo(1) },
  { id: "notif-007", userId: "u-student-001", title: "Sports Day Registration", message: "Annual Sports Day registration is now open. Register before April 30th.", type: "Info", link: "announcements", isRead: false, createdAt: daysAgo(5) },
  { id: "notif-008", userId: "u-teacher-001", title: "New Submission", message: "Sophia Martinez submitted 'Binary Search Tree Implementation' assignment.", type: "Info", link: "assignments", isRead: false, createdAt: daysAgo(1) },
  { id: "notif-009", userId: "u-teacher-001", title: "Attendance Not Marked", message: "You have not marked attendance for today's Database Management Systems class.", type: "Warning", isRead: false, createdAt: daysAgo(0) },
  { id: "notif-010", userId: "u-teacher-001", title: "Meeting Reminder", message: "Department meeting tomorrow at 10:00 AM in Conference Room A.", type: "Info", isRead: true, createdAt: daysAgo(0) },
];

// -------------------- Messages --------------------

export const mockConversations: Conversation[] = [
  {
    id: "conv-001",
    participants: [
      { userId: "u-student-001", name: "Ryan Patel", role: "Student" },
      { userId: "u-teacher-001", name: "Prof. Emily Rodriguez", role: "Teacher" },
    ],
    lastMessage: {
      id: "msg-005",
      senderId: "u-teacher-001",
      senderName: "Prof. Emily Rodriguez",
      receiverId: "u-student-001",
      receiverName: "Ryan Patel",
      content: "Please come to my office during office hours to discuss your project proposal.",
      type: "Direct",
      isRead: false,
      createdAt: daysAgo(0),
    },
    unreadCount: 1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: "conv-002",
    participants: [
      { userId: "u-student-001", name: "Ryan Patel", role: "Student" },
      { userId: "u-student-002", name: "Sophia Martinez", role: "Student" },
    ],
    lastMessage: {
      id: "msg-008",
      senderId: "u-student-002",
      senderName: "Sophia Martinez",
      receiverId: "u-student-001",
      receiverName: "Ryan Patel",
      content: "Hey Ryan, are you done with the graph traversal assignment?",
      type: "Direct",
      isRead: true,
      createdAt: daysAgo(1),
    },
    unreadCount: 0,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: "conv-003",
    participants: [
      { userId: "u-parent-001", name: "Meera Patel", role: "Parent" },
      { userId: "u-teacher-001", name: "Prof. Emily Rodriguez", role: "Teacher" },
    ],
    lastMessage: {
      id: "msg-010",
      senderId: "u-teacher-001",
      senderName: "Prof. Emily Rodriguez",
      receiverId: "u-parent-001",
      receiverName: "Meera Patel",
      content: "Ryan has been doing well in class. His recent midterm score was above average.",
      type: "Direct",
      isRead: true,
      createdAt: daysAgo(3),
    },
    unreadCount: 0,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
];

export const mockMessages: Message[] = [
  { id: "msg-001", senderId: "u-student-001", senderName: "Ryan Patel", receiverId: "u-teacher-001", receiverName: "Prof. Emily Rodriguez", content: "Good morning Professor! I had a question about the BST assignment.", type: "Direct", isRead: true, createdAt: daysAgo(1) },
  { id: "msg-002", senderId: "u-teacher-001", senderName: "Prof. Emily Rodriguez", receiverId: "u-student-001", receiverName: "Ryan Patel", content: "Good morning Ryan! Sure, what's your question?", type: "Direct", isRead: true, createdAt: daysAgo(1) },
  { id: "msg-003", senderId: "u-student-001", senderName: "Ryan Patel", receiverId: "u-teacher-001", receiverName: "Prof. Emily Rodriguez", content: "For the deletion operation, should we handle the case where the node has two children using the in-order successor approach?", type: "Direct", isRead: true, createdAt: daysAgo(1) },
  { id: "msg-004", senderId: "u-teacher-001", senderName: "Prof. Emily Rodriguez", receiverId: "u-student-001", receiverName: "Ryan Patel", content: "Yes, that's the recommended approach. Make sure to handle all three cases: leaf node, one child, and two children.", type: "Direct", isRead: true, createdAt: daysAgo(0) },
  { id: "msg-005", senderId: "u-teacher-001", senderName: "Prof. Emily Rodriguez", receiverId: "u-student-001", receiverName: "Ryan Patel", content: "Please come to my office during office hours to discuss your project proposal.", type: "Direct", isRead: false, createdAt: daysAgo(0) },
  { id: "msg-006", senderId: "u-student-001", senderName: "Ryan Patel", receiverId: "u-student-002", receiverName: "Sophia Martinez", content: "Hey Sophia! How's the database project going?", type: "Direct", isRead: true, createdAt: daysAgo(5) },
  { id: "msg-007", senderId: "u-student-002", senderName: "Sophia Martinez", receiverId: "u-student-001", receiverName: "Ryan Patel", content: "It's going great! Just finished the normalization part. You?", type: "Direct", isRead: true, createdAt: daysAgo(4) },
  { id: "msg-008", senderId: "u-student-002", senderName: "Sophia Martinez", receiverId: "u-student-001", receiverName: "Ryan Patel", content: "Hey Ryan, are you done with the graph traversal assignment?", type: "Direct", isRead: true, createdAt: daysAgo(1) },
  { id: "msg-009", senderId: "u-parent-001", senderName: "Meera Patel", receiverId: "u-teacher-001", receiverName: "Prof. Emily Rodriguez", content: "Hello Professor Rodriguez, I wanted to check on Ryan's progress in your class.", type: "Direct", isRead: true, createdAt: daysAgo(5) },
  { id: "msg-010", senderId: "u-teacher-001", senderName: "Prof. Emily Rodriguez", receiverId: "u-parent-001", receiverName: "Meera Patel", content: "Ryan has been doing well in class. His recent midterm score was above average.", type: "Direct", isRead: true, createdAt: daysAgo(3) },
];

// -------------------- Leave Requests --------------------

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "leave-001",
    studentId: "u-student-001",
    studentName: "Ryan Patel",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    leaveType: "Personal",
    startDate: daysFromNow(5).split("T")[0],
    endDate: daysFromNow(6).split("T")[0],
    days: 2,
    reason: "Family function - attending cousin's wedding",
    status: "Pending",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "leave-002",
    studentId: "u-student-003",
    studentName: "Liam Johnson",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    leaveType: "Medical",
    startDate: daysAgo(2).split("T")[0],
    endDate: daysAgo(1).split("T")[0],
    days: 2,
    reason: "Fever and cold - doctor advised rest",
    status: "Approved",
    approvedBy: "u-teacher-001",
    approvedAt: daysAgo(2),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: "leave-003",
    studentId: "u-student-004",
    studentName: "Emma Thompson",
    batchId: "batch-001",
    batchName: "CS 2023-27",
    leaveType: "Sick",
    startDate: daysFromNow(3).split("T")[0],
    endDate: daysFromNow(4).split("T")[0],
    days: 2,
    reason: "Dental appointment",
    status: "Pending",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
];

// -------------------- Support Tickets --------------------

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "ticket-001",
    userId: "u-student-001",
    userName: "Ryan Patel",
    userRole: "Student",
    subject: "Unable to access online library resources",
    description: "I'm getting a 403 Forbidden error when trying to access the IEEE Xplore digital library through the campus portal. This has been happening since yesterday.",
    category: "Technical",
    priority: "Medium",
    status: "InProgress",
    assignedTo: "u-teacher-003",
    assignedToName: "IT Support Team",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },
  {
    id: "ticket-002",
    userId: "u-student-002",
    userName: "Sophia Martinez",
    userRole: "Student",
    subject: "Grade discrepancy in Linear Algebra",
    description: "My midterm grade for Linear Algebra shows 65 marks but I believe there was an error in evaluating question 3. Could you please recheck?",
    category: "Academic",
    priority: "High",
    status: "Open",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "ticket-003",
    userId: "u-student-005",
    userName: "Noah Williams",
    userRole: "Student",
    subject: "Scholarship application status",
    description: "I submitted my scholarship application 3 weeks ago but haven't received any update. Could you please check the status?",
    category: "Financial",
    priority: "Medium",
    status: "Open",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
];

// -------------------- Document Requests --------------------

export const mockDocumentRequests: DocumentRequest[] = [
  {
    id: "doc-001",
    studentId: "u-student-001",
    studentName: "Ryan Patel",
    documentType: "Transcript",
    purpose: "Graduate school application",
    status: "Pending",
    requestedDate: daysAgo(3).split("T")[0],
    fee: 25,
    createdAt: daysAgo(3),
  },
  {
    id: "doc-002",
    studentId: "u-student-002",
    studentName: "Sophia Martinez",
    documentType: "Bonafide",
    purpose: "Bank loan application",
    status: "Approved",
    requestedDate: daysAgo(10).split("T")[0],
    processedDate: daysAgo(7).split("T")[0],
    processedBy: "u-branch-001",
    remarks: "Document ready for collection at admin office",
    fee: 10,
    createdAt: daysAgo(10),
  },
];

// -------------------- Calendar Events --------------------

export const mockCalendarEvents: CalendarEvent[] = [
  { id: "event-001", title: "Midterm Examinations Begin", description: "Midterm examinations for all semesters", startDate: daysFromNow(20).split("T")[0], endDate: daysFromNow(30).split("T")[0], allDay: true, type: "Exam", color: "#ef4444", createdBy: "u-branch-001" },
  { id: "event-002", title: "Annual Sports Day", description: "Inter-department sports competition", startDate: daysFromNow(25).split("T")[0], endDate: daysFromNow(25).split("T")[0], allDay: true, type: "Event", color: "#10b981", location: "Sports Complex", createdBy: "u-teacher-004" },
  { id: "event-003", title: "Guest Lecture: AI in Healthcare", description: "Invited talk by Dr. Sarah Miller from Stanford", startDate: daysFromNow(5).split("T")[0], endDate: daysFromNow(5).split("T")[0], allDay: false, type: "Academic", color: "#8b5cf6", location: "Auditorium A", createdBy: "u-teacher-001" },
  { id: "event-004", title: "Spring Break", description: "No classes during spring break", startDate: daysFromNow(35).split("T")[0], endDate: daysFromNow(42).split("T")[0], allDay: true, type: "Holiday", color: "#f59e0b", createdBy: "u-branch-001" },
  { id: "event-005", title: "Department Meeting", description: "Monthly CS department meeting", startDate: daysFromNow(2).split("T")[0], endDate: daysFromNow(2).split("T")[0], allDay: false, type: "Meeting", color: "#06b6d4", location: "Conference Room A", createdBy: "u-teacher-001" },
  { id: "event-006", title: "Last Day of Classes", description: "Final day of instruction for Spring semester", startDate: daysFromNow(45).split("T")[0], endDate: daysFromNow(45).split("T")[0], allDay: true, type: "Academic", color: "#ec4899", createdBy: "u-branch-001" },
];

// -------------------- Dashboard Data Helpers --------------------

function createActivityItems(count: number): ActivityItem[] {
  const templates: Omit<ActivityItem, "id" | "timestamp">[] = [
    { type: "assignment", title: "New Assignment Posted", description: "Binary Search Tree Implementation" },
    { type: "grade", title: "Grade Published", description: "Midterm results for Data Structures" },
    { type: "attendance", title: "Attendance Marked", description: "Today's class attendance updated" },
    { type: "announcement", title: "New Announcement", description: "Examination schedule released" },
    { type: "fee", title: "Fee Payment Received", description: "Spring semester tuition payment" },
    { type: "enrollment", title: "New Enrollment", description: "Student enrolled in Machine Learning" },
    { type: "leave", title: "Leave Request Approved", description: "Medical leave for Liam Johnson" },
    { type: "course", title: "Course Updated", description: "New module added to Database Systems" },
  ];

  return Array.from({ length: count }, (_, i) => ({
    id: `activity-${i + 1}`,
    ...templates[i % templates.length],
    timestamp: daysAgo(i),
  }));
}

export function getSuperAdminDashboardData(): SuperAdminDashboardStats {
  return {
    pendingTasks: 8,
    upcomingEvents: 5,
    notifications: 3,
    totalInstitutes: 3,
    totalStudents: 23900,
    totalTeachers: 1620,
    totalBranches: 6,
    revenue: 2850000,
    monthlyGrowth: 4.2,
    activeUsers: 15800,
    systemHealth: "Healthy",
    recentActivity: createActivityItems(8),
    chartsData: {
      enrollmentTrend: [
        { month: "Aug", count: 2800 },
        { month: "Sep", count: 4200 },
        { month: "Oct", count: 3800 },
        { month: "Nov", count: 3500 },
        { month: "Dec", count: 2100 },
        { month: "Jan", count: 4500 },
        { month: "Feb", count: 3000 },
      ],
      revenueTrend: [
        { month: "Aug", amount: 420000 },
        { month: "Sep", amount: 580000 },
        { month: "Oct", amount: 390000 },
        { month: "Nov", amount: 350000 },
        { month: "Dec", amount: 280000 },
        { month: "Jan", amount: 520000 },
        { month: "Feb", amount: 310000 },
      ],
    },
  };
}

export function getInstituteAdminDashboardData(): InstituteAdminDashboardStats {
  return {
    pendingTasks: 12,
    upcomingEvents: 8,
    notifications: 5,
    totalBranches: 3,
    totalStudents: 12500,
    totalTeachers: 850,
    totalCourses: 245,
    monthlyRevenue: 380000,
    attendanceRate: 89.5,
    feeCollection: { collected: 2800000, pending: 450000, overdue: 120000 },
    recentActivity: createActivityItems(10),
    chartsData: {
      branchComparison: [
        { branch: "Main Campus", students: 6200, teachers: 420 },
        { branch: "South Campus", students: 4200, teachers: 310 },
        { branch: "East Campus", students: 2100, teachers: 120 },
      ],
      enrollmentTrend: [
        { month: "Aug", count: 950 },
        { month: "Sep", count: 1800 },
        { month: "Oct", count: 1400 },
        { month: "Nov", count: 1200 },
        { month: "Dec", count: 700 },
        { month: "Jan", count: 1600 },
        { month: "Feb", count: 1100 },
      ],
    },
  };
}

export function getBranchAdminDashboardData(): BranchAdminDashboardStats {
  return {
    pendingTasks: 6,
    upcomingEvents: 4,
    notifications: 4,
    totalStudents: 6200,
    totalTeachers: 420,
    totalCourses: 85,
    totalDepartments: 6,
    attendanceRate: 91.2,
    feeCollection: { collected: 1800000, pending: 280000, overdue: 65000 },
    recentActivity: createActivityItems(8),
    chartsData: {
      departmentStats: [
        { department: "Computer Science", students: 850, teachers: 35 },
        { department: "Business Admin", students: 780, teachers: 28 },
        { department: "Mathematics", students: 420, teachers: 22 },
        { department: "Electrical Engg", students: 390, teachers: 20 },
        { department: "English", students: 340, teachers: 18 },
        { department: "Physics", students: 280, teachers: 15 },
      ],
      attendanceTrend: [
        { week: "Week 1", rate: 92.1 },
        { week: "Week 2", rate: 89.5 },
        { week: "Week 3", rate: 91.8 },
        { week: "Week 4", rate: 93.2 },
        { week: "Week 5", rate: 88.7 },
        { week: "Week 6", rate: 91.2 },
      ],
    },
  };
}

export function getTeacherDashboardData(): TeacherDashboardStats {
  return {
    pendingTasks: 4,
    upcomingEvents: 2,
    notifications: 3,
    totalStudents: 137,
    totalCourses: 2,
    todayClasses: 3,
    pendingGrading: 15,
    attendanceRate: 90.5,
    submissionsToReview: 8,
    upcomingClasses: mockTimetable.slice(0, 3),
    recentActivity: createActivityItems(6),
    chartsData: {
      courseAttendance: [
        { course: "Data Structures", rate: 92 },
        { course: "Machine Learning", rate: 88 },
      ],
      submissionsTrend: [
        { week: "Week 1", submitted: 55, graded: 50 },
        { week: "Week 2", submitted: 48, graded: 52 },
        { week: "Week 3", submitted: 60, graded: 45 },
        { week: "Week 4", submitted: 42, graded: 58 },
      ],
    },
  };
}

export function getStudentDashboardData(): StudentDashboardStats {
  return {
    pendingTasks: 3,
    upcomingEvents: 4,
    notifications: 7,
    enrolledCourses: 3,
    completedCourses: 8,
    overallGPA: 3.52,
    attendanceRate: 91.7,
    upcomingAssignments: mockAssignments.filter(a =>
      new Date(a.dueDate) > new Date()
    ).slice(0, 3),
    recentGrades: mockGrades.filter(g => g.studentId === "u-student-001"),
    pendingFees: 8000,
    attendanceTrend: [
      { week: "Week 1", rate: 95.0 },
      { week: "Week 2", rate: 90.0 },
      { week: "Week 3", rate: 93.3 },
      { week: "Week 4", rate: 88.3 },
      { week: "Week 5", rate: 91.7 },
      { week: "Week 6", rate: 91.7 },
    ],
  };
}

export function getParentDashboardData(): ParentDashboardStats {
  return {
    pendingTasks: 2,
    upcomingEvents: 3,
    notifications: 2,
    childrenCount: 1,
    totalFeesPaid: 28500,
    pendingFees: 8000,
    childrenData: [
      {
        childId: "u-student-001",
        childName: "Ryan Patel",
        attendanceRate: 91.7,
        gpa: 3.52,
        pendingAssignments: 2,
        recentGrade: mockGrades[0],
      },
    ],
  };
}

export function getDashboardData(role: UserRole): DashboardStats {
  const dataMap: Record<UserRole, () => DashboardStats> = {
    SuperAdmin: getSuperAdminDashboardData,
    InstituteAdmin: getInstituteAdminDashboardData,
    BranchAdmin: getBranchAdminDashboardData,
    Teacher: getTeacherDashboardData,
    Student: getStudentDashboardData,
    Parent: getParentDashboardData,
  };
  return dataMap[role]();
}

// -------------------- Aggregated Exports --------------------

export const mockAllData = {
  institutes: mockInstitutes,
  branches: mockBranches,
  departments: mockDepartments,
  programs: mockPrograms,
  academicYears: mockAcademicYears,
  batches: mockBatches,
  students: mockStudents,
  teachers: mockTeachers,
  parents: mockParents,
  adminUsers: mockAdminUsers,
  courses: mockCourses,
  enrollments: mockEnrollments,
  attendanceSessions: mockAttendanceSessions,
  attendanceRecords: mockAttendanceRecords,
  assignments: mockAssignments,
  submissions: mockSubmissions,
  assessments: mockAssessments,
  quizAttempts: mockQuizAttempts,
  grades: mockGrades,
  timetable: mockTimetable,
  feeInvoices: mockFeeInvoices,
  announcements: mockAnnouncements,
  notifications: mockNotifications,
  conversations: mockConversations,
  messages: mockMessages,
  leaveRequests: mockLeaveRequests,
  supportTickets: mockSupportTickets,
  documentRequests: mockDocumentRequests,
  calendarEvents: mockCalendarEvents,
};
